In [16]:
import pandas as pd
import numpy as np
import pickle
filename = "load.csv"

In [17]:
pd.read_csv("/Users/medhaniesolomon/Downloads/LoadingDatasets/load.csv")

         A       B       C        D    E
0    1.276  21.400  63.957  216.204  528
1    1.002  21.950  61.697  204.484  514
2    1.114  22.454  63.522  205.608  514
3    1.133  22.494  61.590  206.565  501
4    0.845  21.654  63.729  201.289  532
..     ...     ...     ...      ...  ...
495  1.060  20.585  60.653  208.990  501
496  1.163  22.629  62.278  200.712  497
497  1.029  21.705  62.311  209.684  517
498  1.114  21.473  65.710  212.078  506
499  1.199  21.586  64.273  208.358  500

[500 rows x 5 columns]

In [20]:
cols = None
data = []
with open(filename) as f:
    for line in f.readlines():
        vals = line.replace("\n", "").split(",")
        if cols is None:
            cols = vals
        else:
            data.append([float(x) for x in vals])
d0 = pd.DataFrame(data, columns=cols)

FileNotFoundError: [Errno 2] No such file or directory: 'load.csv'